import { useAuth } from "@/_core/hooks/useAuth";
import { ArrowRight, CalendarDays, Camera, Mail, ShieldCheck, UserRound, Waves } from "lucide-react";

export default function Profile() {
  const { user, loading } = useAuth({ redirectOnUnauthenticated: true, redirectPath: "/login" });
  if (loading || !user) return <div className="site-auth-loading" dir="rtl"><span className="login-loader" /><p>جارٍ فتح ملفك الشخصي...</p></div>;
  const initials = (user.name || "ز").slice(0, 1);
  return <main className="profile-page" dir="rtl"><div className="profile-wrap"><a href="/" className="profile-back"><ArrowRight size={16} /> العودة للموقع</a><section className="profile-hero"><div className="profile-avatar">{user.profileImage ? <img src={user.profileImage} alt={`الصورة الشخصية لـ ${user.name || "الزائر"}`} /> : <span>{initials}</span>}<span className="profile-avatar-badge"><Camera size={13} /></span></div><div><span className="profile-kicker"><Waves size={15} /> ملف الزائر</span><h1>{user.name || "زائر الموقع"}</h1><p>ملفك الشخصي في بوابة السد العالي</p></div><a href="/articles" className="profile-articles-link">استكشف المقالات <ArrowLeftIcon /></a></section><section className="profile-grid"><div className="profile-panel"><div className="profile-panel-title"><UserRound size={18} /><h2>البيانات الأساسية</h2></div><dl className="profile-details"><div><dt>الاسم الكامل</dt><dd>{user.name || "غير مضاف"}</dd></div><div><dt>البريد الإلكتروني</dt><dd dir="ltr">{user.email || "غير مضاف"}</dd></div><div><dt>تاريخ الميلاد</dt><dd>{user.birthDate || "غير مضاف"}</dd></div><div><dt>طريقة التسجيل</dt><dd>{user.loginMethod === "email" ? "بريد إلكتروني وكلمة مرور" : user.loginMethod || "حساب الموقع"}</dd></div></dl></div><div className="profile-panel profile-status-panel"><div className="profile-panel-title"><ShieldCheck size={18} /><h2>حالة الحساب</h2></div><div className="profile-status"><span className="profile-status-dot" /><strong>{user.role === "admin" ? "مدير الموقع" : "حساب مسجل"}</strong><p>{user.role === "admin" ? "لديك صلاحية الوصول إلى لوحة الإدارة وإحصائيات الزوار." : "يمكنك قراءة الموقع والمقالات وإدارة ملفك الشخصي."}</p></div><div className="profile-meta"><span><CalendarDays size={15} /> آخر دخول</span><strong>{user.lastSignedIn ? new Date(user.lastSignedIn).toLocaleDateString("ar-EG") : "اليوم"}</strong></div><div className="profile-meta"><span><Mail size={15} /> حالة البريد</span><strong>مسجل في الموقع</strong></div></div></section></div></main>;
}

function ArrowLeftIcon() { return <span aria-hidden="true">←</span>; }
